# Numpy Hands and Tutorial

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr,type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


## Mathematical Operations

In [4]:
print(arr +2)

[3 4 5 6 7 8]


In [5]:
print(arr -1)

[0 1 2 3 4 5]


In [6]:
print(arr * 8888)

[ 8888 17776 26664 35552 44440 53328]


In [7]:
print(arr /2)

[0.5 1.  1.5 2.  2.5 3. ]


In [8]:
print(arr // 2)

[0 1 1 2 2 3]
