In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F


print("Pytorch version -> ",torch.__version__)

Pytorch version ->  2.14.0


In [27]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [28]:
# Tensors

x = torch.tensor([1,2,3,4])

print(x)

print(type(x))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [29]:
matrix = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])

print(matrix)

print(type(matrix))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
<class 'torch.Tensor'>


In [30]:
x = torch.randn(3,4)

print("Tensor -> ",x)


print("Shape -> ",x.shape)

print("Device -> ",x.device)

print("Data type -> ",x.dtype)

Tensor ->  tensor([[-0.9595, -1.4943, -0.7382,  0.6868],
        [-0.1314, -0.1920,  1.1727, -0.4314],
        [ 0.2443,  0.7220, -0.4091,  1.0586]])
Shape ->  torch.Size([3, 4])
Device ->  cpu
Data type ->  torch.float32


In [10]:
x_zeroes =torch.zeros(3,4)
print(x_zeroes)
x_ones =torch.ones(3,4)
print(x_ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
x_uniforrm = torch.rand(3,3)
print(x_uniforrm)

tensor([[0.7975, 0.0223, 0.5999],
        [0.3193, 0.5183, 0.7695],
        [0.3194, 0.4372, 0.8137]])


In [12]:
x_normal = torch.randn(4,3)
print(x_normal)

tensor([[-0.7187, -0.4479,  1.0991],
        [ 0.1247, -1.2067,  0.6843],
        [ 0.4908, -0.1712, -0.3043],
        [ 0.5268,  0.4140,  0.5098]])


In [13]:
x = torch.tensor([1,2,3,4,5])
print(f"Second element -> {x[1]}")

Second element -> 2


In [14]:
print(f"Reverse a tensor -> {torch.flip(x,dims=[0])}")

Reverse a tensor -> tensor([5, 4, 3, 2, 1])


In [15]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [16]:
print(f"3rd element in first row {matrix[0,2]}")

3rd element in first row 3


In [17]:
reshape_x = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
x_reshaped = reshape_x.reshape(4,3)
print(x_reshaped)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [18]:
x_view = reshape_x.view(3,4) #Dont use view
print(x_view) 

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [19]:
x = torch.tensor([1,2,3,4])
print(x)
print(x.shape)

print("----------------------------")

x_unsqueeze_0 = x.unsqueeze(0)

x_unsqueeze_1 = x.unsqueeze(1)

print(x_unsqueeze_0)
print(x_unsqueeze_0.shape)
print("----------------------------")
print(x_unsqueeze_1)
print(x_unsqueeze_1.shape)
#

tensor([1, 2, 3, 4])
torch.Size([4])
----------------------------
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
----------------------------
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [20]:
print(x_unsqueeze_0.squeeze(0))
print(x_unsqueeze_0.squeeze(0).shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [21]:
print(x_unsqueeze_1.squeeze(1))
print(x_unsqueeze_1.squeeze(1).shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [22]:
print(x_unsqueeze_0.unsqueeze(2))
print(x_unsqueeze_0.unsqueeze(2).shape)

tensor([[[1],
         [2],
         [3],
         [4]]])
torch.Size([1, 4, 1])


In [23]:
# Permutation
img_hwc = torch.randn(224,224,3)

print(img_hwc.shape)

img_chw = img_hwc.permute(2,0,1)

print(img_chw.shape)


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [24]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [25]:
# Matrix Multiplication

a = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])

b = torch.tensor([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

print(torch.matmul(a,b))

tensor([[ 50,  60],
        [114, 140]])


In [26]:
# Creation of neural network

# input features : 4, output features : 3
# number of hidden layers :2
# number of nodes in each of the hidden layers : 4 and 5
# Activation function : ReLu

class Simple_MLP(nn.Module):
  def __init__(self):
    super().__init__()

    self.mlp_stack = nn.Sequential(
        nn.Linear(4,4),
        nn.ReLU(),
        nn.Linear(4,5),
        nn.ReLU(),
        nn.Linear(5,3)
    )

  def forward(self,x):
    return self.mlp_stack(x)

