In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F


print("Pytorch version -> ",torch.__version__)

Pytorch version ->  2.14.0


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [3]:
# Tensors

x = torch.tensor([1,2,3,4])

print(x)

print(type(x))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [4]:
matrix = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])

print(matrix)

print(type(matrix))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
<class 'torch.Tensor'>


In [5]:
x = torch.randn(3,4)

print("Tensor -> ",x)


print("Shape -> ",x.shape)

print("Device -> ",x.device)

print("Data type -> ",x.dtype)

Tensor ->  tensor([[ 1.2376,  0.7741, -0.1311,  0.2352],
        [-0.9027, -0.0938, -0.5588,  0.7837],
        [ 0.9638, -0.1526, -1.1081,  0.8330]])
Shape ->  torch.Size([3, 4])
Device ->  cpu
Data type ->  torch.float32


In [7]:
x_zeroes =torch.zeros(3,4)
print(x_zeroes)
x_ones =torch.ones(3,4)
print(x_ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
