In [27]:
import numpy as np

In [28]:
a = np.array([1,2,3,4])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [3]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(type(b))

print(b)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print("Shape of a -> ", a.shape)
print("Shape of b -> ", b.shape)

Shape of a ->  (4,)
Shape of b ->  (1, 2)


In [5]:
# Creating random np arrays

all_zeros = np.zeros((3,3))

print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
all_zeros_v2 = np.zeros_like(b)

print(all_zeros_v2)

[[0. 0.]]


In [7]:
all_ones = np.ones((3,3))

print(all_ones)

all_ones_v2 = np.ones_like(b)

print(all_ones_v2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [31]:
arr_uniform = np.random.uniform(2,5,(3,3))

print(arr_uniform)

[[2.62949718 3.03151063 4.78859937]
 [3.79515038 4.89127674 3.4058599 ]
 [2.37124702 2.24382502 4.96646922]]


In [9]:
arr_normal = np.random.normal(1,2,(3,3))

print(arr_normal)

[[ 0.17388336  0.87951651  2.27042571]
 [-1.83616671 -2.30192451  3.11286414]
 [ 1.20299707  0.34714805  1.84218309]]


In [32]:
# Indexing in Numpy arrays

x = np.array([1,2,3,4,5,6,7])

print(x[0])
print(x[-1])
print(x[1:4])
print(x[::2])
print(x[::-1])

1
7
[2 3 4]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [11]:
x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Access the row 2 -> ",x2[1])
print("Access the column 2 -> ",x2[:,1])
print("Access the row 2 and column 2 -> ",x2[1,1])
print("Access the row 2 and column 2 and 3 -> ",x2[1,1:3])
print(x2[:2,:2])

Access the row 2 ->  [5 6 7 8]
Access the column 2 ->  [ 2  6 10]
Access the row 2 and column 2 ->  6
Access the row 2 and column 2 and 3 ->  [6 7]
[[1 2]
 [5 6]]


In [33]:
# Reshaping
# Vector to matrix

x = np.array([1,2,3,4,5,6,7,8])

x_reshaped = x.reshape(4,2)

print(x_reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# matrix to array

y = np.random.uniform(1,2,(3,3))
print(y)

y_flatten = y.flatten()

print(y_flatten)

[[1.94147533 1.18878482 1.36956862]
 [1.96637482 1.45238816 1.18192357]
 [1.02535081 1.84616765 1.89002708]]
[1.94147533 1.18878482 1.36956862 1.96637482 1.45238816 1.18192357
 1.02535081 1.84616765 1.89002708]


In [34]:
# Some Arthematic operations

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [15]:
# Broadcasting

a = np.array([1,2,3,4])
b = 2

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [35]:
# Broadcasting with matrices

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6  8]
 [ 6  8 10 12]]
[[0 0 0 0]
 [4 4 4 4]]
[[ 1  4  9 16]
 [ 5 12 21 32]]
[[1.         1.         1.         1.        ]
 [5.         3.         2.33333333 2.        ]]


In [17]:
# Matrix Multiplication

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

print(np.matmul(a,b))

[[ 50  60]
 [114 140]]


In [18]:
# Manual implementaion of one pass through the layer
# in features = 3
# out features = 2

w = np.random.normal(0,1,(3,2))

b = np.random.uniform(0,1,(1,2))

x = np.array([1,2,3])

print(w)
print("----------------")

print(b)
print("----------------")

print(x @ w + b)

[[ 0.64279607  0.1358524 ]
 [ 0.19936544  0.13776382]
 [-0.13048299 -1.45017283]]
----------------
[[0.93088586 0.22982315]]
----------------
[[ 1.58096383 -3.7093153 ]]


In [19]:
# for a batch of example

x = np.random.uniform(0,1,(4,3))

print(x)

print("----------------")

print(x @ w + b)

[[0.02191197 0.13498039 0.36455337]
 [0.26061165 0.22444319 0.34778089]
 [0.90489302 0.32585638 0.22511258]
 [0.29337303 0.36798719 0.66269483]]
----------------
[[ 0.9243132  -0.27727003]
 [ 1.09777273 -0.20819437]
 [ 1.54813867  0.07119411]
 [ 1.10635841 -0.64064813]]


In [20]:
# Implementing Activation Functions


# ReLu Activation

def relu(x):
  return np.maximum(0,x)

x = np.array([0,-2.12,3,3.8,-0.001])

print(relu(x))

[0.  0.  3.  3.8 0. ]


In [21]:
# Sigmoid Activation

def sigmoid(x):
  return 1/(1+np.exp(-x))

print(sigmoid(x))

[0.5        0.10716807 0.95257413 0.97811873 0.49975   ]


In [22]:
# Tanh activation

def tanh(x):
  return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))

print(tanh(x))

[ 0.         -0.97159408  0.99505475  0.9989996  -0.001     ]


In [23]:
# Softmax function

def softmax(x):
  exp_x = np.exp(x-np.max(x))
  return exp_x / np.sum(exp_x)

print(softmax(x))
print(np.sum(softmax(x)))

[0.0149464  0.00179404 0.30020642 0.66812168 0.01493146]
1.0


In [24]:
np.exp(x-np.max(x))

array([0.02237077, 0.0026852 , 0.44932896, 1.        , 0.02234841])

In [26]:
np.exp(x-np.max(x)) / np.sum(np.exp(x-np.max(x)))

array([0.0149464 , 0.00179404, 0.30020642, 0.66812168, 0.01493146])