In [44]:
import numpy as np

In [45]:
a = np.array([1,2,3,4])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [46]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(type(b))

print(b)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [47]:
print("Shape of a -> ", a.shape)
print("Shape of b -> ", b.shape)

Shape of a ->  (4,)
Shape of b ->  (2, 4)


In [48]:
# Creating random np arrays

all_zeros = np.zeros((3,3))

print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
all_zeros_v2 = np.zeros_like(b)

print(all_zeros_v2)

[[0 0 0 0]
 [0 0 0 0]]


In [50]:
all_ones = np.ones((3,3))

print(all_ones)

all_ones_v2 = np.ones_like(b)

print(all_ones_v2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [31]:
arr_uniform = np.random.uniform(2,5,(3,3))

print(arr_uniform)

[[2.62949718 3.03151063 4.78859937]
 [3.79515038 4.89127674 3.4058599 ]
 [2.37124702 2.24382502 4.96646922]]


In [9]:
arr_normal = np.random.normal(1,2,(3,3))

print(arr_normal)

[[ 0.17388336  0.87951651  2.27042571]
 [-1.83616671 -2.30192451  3.11286414]
 [ 1.20299707  0.34714805  1.84218309]]


In [32]:
# Indexing in Numpy arrays

x = np.array([1,2,3,4,5,6,7])

print(x[0])
print(x[-1])
print(x[1:4])
print(x[::2])
print(x[::-1])

1
7
[2 3 4]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [11]:
x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Access the row 2 -> ",x2[1])
print("Access the column 2 -> ",x2[:,1])
print("Access the row 2 and column 2 -> ",x2[1,1])
print("Access the row 2 and column 2 and 3 -> ",x2[1,1:3])
print(x2[:2,:2])

Access the row 2 ->  [5 6 7 8]
Access the column 2 ->  [ 2  6 10]
Access the row 2 and column 2 ->  6
Access the row 2 and column 2 and 3 ->  [6 7]
[[1 2]
 [5 6]]


In [33]:
# Reshaping
# Vector to matrix

x = np.array([1,2,3,4,5,6,7,8])

x_reshaped = x.reshape(4,2)

print(x_reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# matrix to array

y = np.random.uniform(1,2,(3,3))
print(y)

y_flatten = y.flatten()

print(y_flatten)

[[1.94147533 1.18878482 1.36956862]
 [1.96637482 1.45238816 1.18192357]
 [1.02535081 1.84616765 1.89002708]]
[1.94147533 1.18878482 1.36956862 1.96637482 1.45238816 1.18192357
 1.02535081 1.84616765 1.89002708]


In [34]:
# Some Arthematic operations

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [15]:
# Broadcasting

a = np.array([1,2,3,4])
b = 2

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [35]:
# Broadcasting with matrices

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6  8]
 [ 6  8 10 12]]
[[0 0 0 0]
 [4 4 4 4]]
[[ 1  4  9 16]
 [ 5 12 21 32]]
[[1.         1.         1.         1.        ]
 [5.         3.         2.33333333 2.        ]]


In [17]:
# Matrix Multiplication

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

print(np.matmul(a,b))

[[ 50  60]
 [114 140]]


In [36]:
# Manual implementaion of one pass through the layer
# in features = 3
# out features = 2

w = np.random.normal(0,1,(3,2))

b = np.random.uniform(0,1,(1,2))

x = np.array([1,2,3])

print(w)
print("----------------")

print(b)
print("----------------")

print(x @ w + b)

[[-0.69966332  1.63541267]
 [ 1.22931543  0.55324121]
 [ 1.02154445 -0.10407697]]
----------------
[[0.26985576 0.80805621]]
----------------
[[5.09345665 3.23772039]]


In [37]:
# for a batch of example

x = np.random.uniform(0,1,(4,3))

print(x)

print("----------------")

print(x @ w + b)

[[0.16946489 0.60875254 0.79268142]
 [0.82602098 0.2866659  0.68958895]
 [0.73766678 0.54906178 0.40614355]
 [0.16322071 0.14828854 0.53530556]]
----------------
[[1.70939559 1.33948835]
 [0.74876776 2.24576644]
 [0.84360119 2.27593922]
 [0.88478803 1.10131578]]


In [20]:
# Implementing Activation Functions


# ReLu Activation

def relu(x):
  return np.maximum(0,x)

x = np.array([0,-2.12,3,3.8,-0.001])

print(relu(x))

[0.  0.  3.  3.8 0. ]


In [38]:
# Sigmoid Activation

def sigmoid(x):
  return 1/(1+np.exp(-x))

print(sigmoid(x))

[[0.54226512 0.64765619 0.68840679]
 [0.69551293 0.5711797  0.66587548]
 [0.67648544 0.63391789 0.60016282]
 [0.54071483 0.53700435 0.6307197 ]]


In [22]:
# Tanh activation

def tanh(x):
  return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))

print(tanh(x))

[ 0.         -0.97159408  0.99505475  0.9989996  -0.001     ]


In [39]:
# Softmax function

def softmax(x):
  exp_x = np.exp(x-np.max(x))
  return exp_x / np.sum(exp_x)

print(softmax(x))
print(np.sum(softmax(x)))

[[0.058618   0.09095177 0.1093177 ]
 [0.11302373 0.06590687 0.09860932]
 [0.10346606 0.08568165 0.07427099]
 [0.05825312 0.05738973 0.08451106]]
1.0


In [24]:
np.exp(x-np.max(x))

array([0.02237077, 0.0026852 , 0.44932896, 1.        , 0.02234841])

In [40]:
np.exp(x-np.max(x)) / np.sum(np.exp(x-np.max(x)))

array([[0.058618  , 0.09095177, 0.1093177 ],
       [0.11302373, 0.06590687, 0.09860932],
       [0.10346606, 0.08568165, 0.07427099],
       [0.05825312, 0.05738973, 0.08451106]])

In [41]:
# MLP

# input -> Hidden -> ReLu -> Logits -> Prob vector

# input is 4 features

# output is 3 features

# hidden is 7 features

w1 = np.random.normal(1,2,(4,7))

w2 = np.random.normal(1,2,(7,3))

b1 = np.random.uniform(0,1,(1,7))

b2 = np.random.uniform(0,1,(1,3))

# batch size of 64

x = np.random.normal(0,1,(3,4))

z1 = x @ w1 + b1

a1 = relu(z1)

z2 = a1 @ w2 + b2

a2 = softmax(z2)

print(a2)

print(np.sum(a2))


[[3.44260661e-10 8.17333664e-21 1.73024913e-18]
 [9.99999996e-01 3.94156280e-09 5.14411336e-15]
 [3.07894412e-11 2.80434318e-24 7.07671391e-21]]
1.0


In [42]:
# MSE Error


def mse(y_true,y_pred):
  return np.mean((y_true-y_pred)**2)

y_true = np.array([1,2,3,4])

y_pred = np.array([1,2,3,4])

print(mse(y_true,y_pred))

0.0


In [43]:
# CCE Loss

def cce_loss(y_true,y_pred):
  return -np.mean(y_true*np.log(y_pred))

y_true = np.array([1,0,0])

y_pred = np.array([0.9,0.05,0.05])

print(cce_loss(y_true,y_pred))


0.035120171885942096
