In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [3]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(type(b))

print(b)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print("Shape of a -> ", a.shape)
print("Shape of b -> ", b.shape)

Shape of a ->  (4,)
Shape of b ->  (2, 4)


In [5]:
# Creating random np arrays

all_zeros = np.zeros((3,3))

print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
all_zeros_v2 = np.zeros_like(b)

print(all_zeros_v2)

[[0 0 0 0]
 [0 0 0 0]]


In [7]:
all_ones = np.ones((3,3))

print(all_ones)

all_ones_v2 = np.ones_like(b)

print(all_ones_v2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [8]:
arr_uniform = np.random.uniform(2,5,(3,3))

print(arr_uniform)

[[2.09202062 4.88540622 3.87767789]
 [4.10508686 2.39473998 3.38100701]
 [3.30290755 2.90488629 4.3746623 ]]


In [9]:
arr_normal = np.random.normal(1,2,(3,3))

print(arr_normal)

[[ 0.17388336  0.87951651  2.27042571]
 [-1.83616671 -2.30192451  3.11286414]
 [ 1.20299707  0.34714805  1.84218309]]


In [10]:
# Indexing in Numpy arrays

x = np.array([1,2,3,4,5,6,7])

print(x[0])
print(x[-1])
print(x[1:4])
print(x[::2])
print(x[::-1])

1
7
[2 3 4]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [11]:
x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Access the row 2 -> ",x2[1])
print("Access the column 2 -> ",x2[:,1])
print("Access the row 2 and column 2 -> ",x2[1,1])
print("Access the row 2 and column 2 and 3 -> ",x2[1,1:3])
print(x2[:2,:2])

Access the row 2 ->  [5 6 7 8]
Access the column 2 ->  [ 2  6 10]
Access the row 2 and column 2 ->  6
Access the row 2 and column 2 and 3 ->  [6 7]
[[1 2]
 [5 6]]


In [12]:
# Reshaping
# Vector to matrix

x = np.array([1,2,3,4,5,6,7,8])

x_reshaped = x.reshape(4,2)

print(x_reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# matrix to array

y = np.random.uniform(1,2,(3,3))
print(y)

y_flatten = y.flatten()

print(y_flatten)

[[1.94147533 1.18878482 1.36956862]
 [1.96637482 1.45238816 1.18192357]
 [1.02535081 1.84616765 1.89002708]]
[1.94147533 1.18878482 1.36956862 1.96637482 1.45238816 1.18192357
 1.02535081 1.84616765 1.89002708]


In [14]:
# Some Arthematic operations

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
