In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [3]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(type(b))

print(b)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print("Shape of a -> ", a.shape)
print("Shape of b -> ", b.shape)

Shape of a ->  (4,)
Shape of b ->  (2, 4)


In [5]:
# Creating random np arrays

all_zeros = np.zeros((3,3))

print(all_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
all_zeros_v2 = np.zeros_like(b)

print(all_zeros_v2)

[[0 0 0 0]
 [0 0 0 0]]


In [7]:
all_ones = np.ones((3,3))

print(all_ones)

all_ones_v2 = np.ones_like(b)

print(all_ones_v2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [8]:
arr_uniform = np.random.uniform(2,5,(3,3))

print(arr_uniform)

[[2.38931448 4.61654546 4.6652412 ]
 [3.00719326 4.53042479 3.71156166]
 [4.35589634 3.64744682 3.98567018]]


In [9]:
arr_normal = np.random.normal(1,2,(3,3))

print(arr_normal)

[[ 3.22112602 -2.48562945  0.85301195]
 [-3.20026293 -1.29174279  0.86883664]
 [ 3.05081834  1.57810505  0.68860891]]


In [10]:
# Indexing in Numpy arrays

x = np.array([1,2,3,4,5,6,7])

print(x[0])
print(x[-1])
print(x[1:4])
print(x[::2])
print(x[::-1])

1
7
[2 3 4]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [11]:
x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Access the row 2 -> ",x2[1])
print("Access the column 2 -> ",x2[:,1])
print("Access the row 2 and column 2 -> ",x2[1,1])
print("Access the row 2 and column 2 and 3 -> ",x2[1,1:3])
print(x2[:2,:2])

Access the row 2 ->  [5 6 7 8]
Access the column 2 ->  [ 2  6 10]
Access the row 2 and column 2 ->  6
Access the row 2 and column 2 and 3 ->  [6 7]
[[1 2]
 [5 6]]


In [12]:
# Reshaping
# Vector to matrix

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

x_reshaped = x.reshape(3,4)

print(x_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# matrix to array

y = np.random.uniform(1,2,(3,3))
print(y)

y_flatten = y.flatten()

print(y_flatten)

[[1.28702141 1.64735367 1.93860093]
 [1.78792605 1.39858574 1.37799201]
 [1.2252897  1.61592486 1.0161242 ]]
[1.28702141 1.64735367 1.93860093 1.78792605 1.39858574 1.37799201
 1.2252897  1.61592486 1.0161242 ]


In [14]:
# Some Arthematic operations

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [15]:
# Broadcasting

a = np.array([1,2,3,4])
b = 2

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [16]:
# Broadcasting with matrices

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6  8]
 [ 6  8 10 12]]
[[0 0 0 0]
 [4 4 4 4]]
[[ 1  4  9 16]
 [ 5 12 21 32]]
[[1.         1.         1.         1.        ]
 [5.         3.         2.33333333 2.        ]]


In [17]:
# Matrix Multiplication

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

b = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

print(np.matmul(a,b))

[[ 50  60]
 [114 140]]


In [18]:
# Manual implementaion of one pass through the layer
# in features = 3
# out features = 2

w = np.random.normal(0,1,(3,2))

b = np.random.uniform(0,1,(1,2))

x = np.array([1,2,3])

print(w)
print("----------------")

print(b)
print("----------------")

print(x @ w + b)

[[-0.88483187  0.77343695]
 [ 0.4341457   0.62489761]
 [-0.69709766 -0.16313761]]
----------------
[[0.48090857 0.65260059]]
----------------
[[-1.62692487  2.18641994]]


In [19]:
# for a batch of example

x = np.random.uniform(0,1,(4,3))

print(x)

print("----------------")

print(x @ w + b)

[[0.5075453  0.66291621 0.14181012]
 [0.16726748 0.51951037 0.90076391]
 [0.52230722 0.11420579 0.98076549]
 [0.13621527 0.30508367 0.99786425]]
----------------
[[ 0.22076303  1.43627507]
 [-0.06947224  0.95966376]
 [-0.61535287  0.96793949]
 [-0.20277711  0.78581139]]


In [20]:
# Implementing Activation Functions


# ReLu Activation

def relu(x):
  return np.maximum(0,x)

x = np.array([0,-2.12,3,3.8,-0.001])

print(relu(x))

[0.  0.  3.  3.8 0. ]


In [21]:
# Sigmoid Activation

def sigmoid(x):
  return 1/(1+np.exp(-x))

print(sigmoid(x))

[0.5        0.10716807 0.95257413 0.97811873 0.49975   ]


In [22]:
# Tanh activation

def tanh(x):
  return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))

print(tanh(x))

[ 0.         -0.97159408  0.99505475  0.9989996  -0.001     ]


In [23]:
# Softmax function

def softmax(x):
  exp_x = np.exp(x-np.max(x))
  return exp_x / np.sum(exp_x)

print(softmax(x))
print(np.sum(softmax(x)))

[0.0149464  0.00179404 0.30020642 0.66812168 0.01493146]
1.0


In [24]:
np.exp(x-np.max(x))

array([0.02237077, 0.0026852 , 0.44932896, 1.        , 0.02234841])

In [25]:
np.exp(x-np.max(x)) / np.sum(np.exp(x-np.max(x)))

array([0.0149464 , 0.00179404, 0.30020642, 0.66812168, 0.01493146])

In [32]:
# MLP

# input -> Hidden -> ReLu -> Logits -> Prob vector

# input is 4 features

# output is 3 features

# hidden is 7 features

w1 = np.random.normal(1,2,(4,7))

w2 = np.random.normal(1,2,(7,3))

b1 = np.random.uniform(0,1,(1,7))

b2 = np.random.uniform(0,1,(1,3))

# batch size of 64

x = np.random.normal(0,1,(3,4))

z1 = x @ w1 + b1

a1 = relu(z1)

z2 = a1 @ w2 + b2

a2 = softmax(z2)

print(a2)

print(np.sum(a2))


[[9.99592414e-01 6.36542612e-07 4.05597049e-04]
 [1.34717104e-06 3.14170280e-09 2.99505675e-11]
 [2.28119011e-10 9.63172289e-13 1.56907720e-09]]
1.0


In [27]:
# MSE Error


def mse(y_true,y_pred):
  return np.mean((y_true-y_pred)**2)

y_true = np.array([1,2,3,4])

y_pred = np.array([1,2,3,4])

print(mse(y_true,y_pred))

0.0


In [28]:
# CCE Loss

def cce_loss(y_true,y_pred):
  return -np.mean(y_true*np.log(y_pred))

y_true = np.array([1,0,0])

y_pred = np.array([0.9,0.05,0.05])

print(cce_loss(y_true,y_pred))


0.035120171885942096
