# ===== CORE PYTHON (1-7) =====

In [3]:
# 1. Count Even and Odd
# Given a list, return how many even and how many odd numbers it has.
# Example: [1, 2, 3, 4, 5, 6] -> even: 3, odd: 3
nums = [1, 2, 3, 4, 5, 6]
from collections import Counter
counts = Counter("Even" if x%2 == 0 else "Odd" for x in nums)
print(counts)

Counter({'Odd': 3, 'Even': 3})


In [5]:
# 2. Title Case a Sentence
# Capitalize the first letter of each word without using .title().
# Example: "hello world from python" -> "Hello World From Python"
sentence = "hello world from python"
print(" ".join([x.capitalize() for x in sentence.split()]))

Hello World From Python


In [9]:
# 3. Find Common Elements
# Return elements present in both lists.
# Example: [1, 2, 3, 4], [3, 4, 5, 6] -> [3, 4]
a = [1, 2, 3, 4]
b = [3, 4, 5, 6]
print(f"Common Elements -> {list(set(a)&set(b))}")

Common Elements -> [3, 4]


In [13]:
# 4. Count Vowels and Consonants
# Given a string, count vowels and consonants separately (letters only).
# Example: "hello" -> vowels: 2, consonants: 3
text = "hello"
from collections import Counter
counts = Counter("vowels" if x.lower() in 'aeiou' else 'consonants' for x in text if x.isalpha())
print(counts)

Counter({'consonants': 3, 'vowels': 2})


In [15]:
# 5. Sum of Even Numbers
# Return the sum of only the even numbers in a list.
# Example: [1, 2, 3, 4, 5, 6] -> 12
values = [1, 2, 3, 4, 5, 6]
print(f"Sum of even Nos -> :{sum([x for x in values if x%2 == 0])}")

Sum of even Nos -> :12


In [58]:
# 6. Dictionary From Two Lists
# Build a dictionary pairing keys with values.
# Example: ["a", "b", "c"], [1, 2, 3] -> {"a": 1, "b": 2, "c": 3}
keys = ["a", "b", "c"]
vals = [1, 2, 3]
{k:v for k,v in zip(keys,vals)}

{'a': 1, 'b': 2, 'c': 3}

In [21]:
# 7. Remove Punctuation
# Return the string with all punctuation removed.
# Example: "Hello, World! How are you?" -> "Hello World How are you"
line = "Hello, World! How are you?"
import re
new_line = re.sub(r'[^a-zA-Z0-9 ]','',line)
new_line

'Hello World How are you'

# ===== NUMPY (8-14) =====

In [24]:
# 8. Count Values Above Mean
# Return how many elements in the array are greater than the mean.
# Example: [10, 20, 30, 40, 50] -> 2
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr[arr>arr.mean()]

array([40, 50])

In [26]:
# 9. Element-wise Operations
# Given two arrays, return their element-wise sum, difference, and product.
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(f"Sum:{x+y}\nDifference:{abs(x-y)}\nProduct:{x*y}")

Sum:[ 6  8 10 12]
Difference:[4 4 4 4]
Product:[ 5 12 21 32]


In [28]:
# 10. Replace Odd Numbers With -1
# Keep even numbers, replace all odd numbers with -1.
# Example: [1, 2, 3, 4, 5] -> [-1, 2, -1, 4, -1]
import numpy as np
data = np.array([1, 2, 3, 4, 5])
print([-1 if x%2 != 0 else x for x in data])

[-1, np.int64(2), -1, np.int64(4), -1]


In [34]:
# 11. Column-wise Mean of a Matrix
# Return the mean of each column in the 2D array.
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix.mean(axis=0)

array([4., 5., 6.])

In [35]:
# 12. Find Index of Maximum
# Return the index position of the largest value.
# Example: [3, 7, 1, 9, 4] -> 3
import numpy as np
vec = np.array([3, 7, 1, 9, 4])
vec.argmax()

np.int64(3)

In [37]:
# 13. Standardize an Array (Z-score)
# Transform the array so it has mean 0 and std 1.
import numpy as np
sample = np.array([10, 12, 14, 16, 18])
sample = (sample - sample.mean())/ sample.std()
print(sample.mean(),sample.std())

0.0 0.9999999999999999


In [39]:
# 14. Count Nonzero Elements
# Return how many elements are not zero.
# Example: [0, 3, 0, 5, 0, 7] -> 3
import numpy as np
signal = np.array([0, 3, 0, 5, 0, 7])
len(signal[signal>0])

3

In [41]:
# 15. Select Columns and Rename
# Keep only "name" and "salary", rename "salary" to "monthly_salary".
import pandas as pd
emp = pd.DataFrame({
    "name": ["Arjun", "Priya", "Karan"],
    "dept": ["IT", "HR", "Finance"],
    "salary": [50000, 45000, 60000],
})
emp = emp.rename(columns=({'salary':'monthly_salary'}))
emp

,name,dept,monthly_salary
0,Arjun,IT,50000
1,Priya,HR,45000
2,Karan,Finance,60000


In [47]:
# 16. Count Unique Values
# Return how many times each category appears in the "category" column.
import pandas as pd
items = pd.DataFrame({
    "category": ["A", "B", "A", "C", "B", "A"],
})
items['category'].value_counts()

category
A    3
B    2
C    1
Name: count, dtype: int64

In [53]:
# 17. Filter on Two Conditions
# Return rows where age > 25 AND city is "Chennai".
import pandas as pd
df = pd.DataFrame({
    "name": ["Ram", "Sita", "Gita", "Shyam"],
    "age": [30, 22, 28, 35],
    "city": ["Chennai", "Chennai", "Mumbai", "Chennai"],
})
df[(df['city']=='Chennai') & (df['age']>25)]

,name,age,city
0,Ram,30,Chennai
3,Shyam,35,Chennai


In [54]:
# 18. Sort by Multiple Columns
# Sort by dept ascending, then salary descending.
import pandas as pd
staff = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "dept": ["IT", "HR", "IT", "HR"],
    "salary": [50000, 45000, 70000, 48000],
})
staff.sort_values(by=['dept','salary'],ascending=[True,False])

,name,dept,salary
3,D,HR,48000
1,B,HR,45000
2,C,IT,70000
0,A,IT,50000


In [56]:

# 19. Group and Mean
# Return the average score per subject.
import pandas as pd
scores = pd.DataFrame({
    "subject": ["Math", "Science", "Math", "Science", "Math"],
    "score": [80, 90, 70, 85, 95],
})

scores.groupby('subject').agg(mean_score = ('score','mean')).reset_index()


,subject,mean_score
0,Math,81.666667
1,Science,87.500000


In [57]:
# 20. Apply a Custom Function
# Add a "grade" column: A if score >= 90, B if >= 75, else C.
import pandas as pd
results = pd.DataFrame({
    "student": ["P", "Q", "R", "S"],
    "score": [92, 78, 65, 88],
})
def grader(mark):
    if mark >= 90:
        return "A"
    elif mark <90 and mark >= 75:
        return "B"
    else:
        return "C"

results['grade'] = results['score'].apply(grader)
results

,student,score,grade
0,P,92,A
1,Q,78,B
2,R,65,C
3,S,88,B


# ===== CORE PYTHON (1-3) =====

In [7]:
# 1. First Non-Repeating Character
# Return the first character that appears exactly once in the string.
# Example: "swiss" -> "w"
from collections import defaultdict
s = "swiss"
char_count = defaultdict(list)
for char in s:
    char_count[char] = char_count.get(char,0)+1
for i,j in char_count.items():
    if j==1:
        print(f'First Non repeating character is "{i}"')
        break

First Non repeating character is w


In [13]:
# 2. Merge Overlapping Counts
# Given a list of (name, score) tuples, sum scores per name.
# Example: [("a", 10), ("b", 5), ("a", 7)] -> {"a": 17, "b": 5}
from collections import Counter
pairs = [("a", 10), ("b", 5), ("a", 7), ("c", 3), ("b", 2)]
overlapping = {}
for i,j in pairs:
    overlapping[i] = overlapping.get(i,0)+j
print(overlapping)

{'a': 17, 'b': 7, 'c': 3}


In [14]:
# 3. Running Maximum
# Return a list where each element is the max seen so far.
# Example: [3, 1, 4, 1, 5, 9, 2] -> [3, 3, 4, 4, 5, 9, 9]
nums = [3, 1, 4, 1, 5, 9, 2]
current_max = nums[0]
lst = []
for i in nums:
    current_max = max(current_max,i)
    lst.append(current_max)
print(lst)


[3, 3, 4, 4, 5, 9, 9]


In [21]:
# ===== NUMPY (4-6) =====

# 4. Row-wise Normalization
# Normalize each row of the matrix so its values sum to 1.
import numpy as np
matrix = np.array([[1, 1, 2], [2, 3, 5], [4, 4, 2]])
row_sums = matrix.sum(axis=1,keepdims=True)
normalized = np.divide(matrix,row_sums,np.zeros_like(matrix,dtype=np.float64),where=row_sums!=0)
normalized

array([[0.25, 0.25, 0.5 ],
       [0.2 , 0.3 , 0.5 ],
       [0.4 , 0.4 , 0.2 ]])

In [24]:
# 5. Clip and Count
# Clip all values to the range [20, 80], then count how many got changed.
import numpy as np
arr = np.array([5, 25, 90, 60, 15, 100, 40])
len(arr.clip(20,80))

7

In [25]:
# 6. Pairwise Euclidean Distance
# Given points, return the distance between the first point and every other point.
# Example: [[0,0],[3,4],[6,8]] -> [0.0, 5.0, 10.0]
import numpy as np
points = np.array([[0, 0], [3, 4], [6, 8]])
distances = np.linalg.norm(points - points[0], axis=1)
distances

array([ 0.,  5., 10.])

In [26]:
# 7. Merge Two DataFrames
# Join orders with customers on customer_id. Keep all orders.
import pandas as pd
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Arjun", "Priya", "Karan"],
})
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 2, 1, 3],
    "amount": [500, 300, 700, 200],
})
pd.merge(left=customers,right=orders,how='right')

,customer_id,name,order_id,amount
0,1,Arjun,101,500
1,2,Priya,102,300
2,1,Arjun,103,700
3,3,Karan,104,200


In [28]:
# 8. Group, Aggregate, Multiple Metrics
# Per region, return total and average amount in one result.
import pandas as pd
sales = pd.DataFrame({
    "region": ["S", "N", "S", "W", "N", "S"],
    "amount": [250, 400, 300, 150, 500, 200],
})
sales.groupby('region').agg(total_sales=('amount','sum'),average_amount=('amount','mean')).reset_index()

,region,total_sales,average_amount
0,N,900,450.0
1,S,750,250.0
2,W,150,150.0


In [29]:
# 9. Pivot Table
# Reshape so rows are "product", columns are "month", values are "units" sold.
import pandas as pd
data = pd.DataFrame({
    "product": ["A", "A", "B", "B", "A", "B"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Jan", "Feb"],
    "units": [10, 15, 5, 8, 12, 6],
})
pd.pivot_table(
    data = data,
    values = 'units',
    index= 'product',
    columns='month'
)

month,Feb,Jan
product,,
A,15.0,11.0
B,7.0,5.0


In [31]:
# 10. Rank Within Group
# Add a column ranking employees by salary within each department (1 = highest).
import pandas as pd
emp = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "dept": ["IT", "IT", "HR", "HR", "IT"],
    "salary": [50000, 70000, 45000, 48000, 60000],
})
emp['rank'] = emp.groupby('dept')['salary'].rank(method='dense',ascending=False)
emp

,name,dept,salary,rank
0,A,IT,50000,3.0
1,B,IT,70000,1.0
2,C,HR,45000,2.0
3,D,HR,48000,1.0
4,E,IT,60000,2.0


In [36]:
# 1. Count Characters Ignoring Spaces  [Service / screening]
# Return a dict of character counts, skipping spaces.
# Example: "data science" -> {'d':1,'a':2,'t':1,'s':2,'c':2,'i':1,'e':2,'n':1}
from collections import Counter
text = "data science"
counts = Counter("".join(text.split()))
counts

Counter({'a': 2, 'c': 2, 'e': 2, 'd': 1, 't': 1, 's': 1, 'i': 1, 'n': 1})

In [38]:
# 2. Find Duplicates in a List  [Service / screening]
# Return the values that appear more than once.
# Example: [1,2,3,2,4,5,5,5] -> [2, 5]
from collections import Counter
nums = [1, 2, 3, 2, 4, 5, 5, 5]
counts = Counter(nums)
[k for k,v in counts.items() if v>1]


[2, 5]