# Students Mark Analaysis
1.Average Mark by subject and student

2.Highest and lowest per subject

3.Overall Class Topper

4.Paas Count per subject

5.Which subject is difficult

6.Ranking Students

In [2]:
import numpy as np
from numpy.linalg import inv,det

In [6]:
np.random.seed(25)
marks = np.random.randint(10,101,size=(20,5))
marks

array([[ 14,  72, 100,  25,  71],
       [ 33,  54,  60,  18,  38],
       [ 14,  99,  41,  79,  11],
       [ 49,  13,  98,  65,  13],
       [ 94,  55,  13,  11,  32],
       [ 41,  58,  57,  83,  26],
       [ 60,  95,  46,  19,  42],
       [ 20,  70,  57,  11,  96],
       [ 59,  28,  46,  40,  48],
       [ 12,  15,  67,  83,  32],
       [ 21,  12,  53, 100,  71],
       [ 94,  93,  84,  27,  24],
       [ 93,  47,  97,  60,  61],
       [ 24,  81,  72, 100,  25],
       [ 24,  86,  49,  98,  56],
       [ 63,  39,  23,  56,  63],
       [ 72,  77,  12,  54,  54],
       [ 73,  55,  34,  19,  77],
       [ 69,  89,  42,  15,  66],
       [ 46,  93,  29,  21,  47]])

In [9]:
#1.Average Mark by subject and student
average_by_subject = np.mean(marks,axis=0)
average_by_studnet = np.mean(marks,axis=1)
print(f"The average mark per subject is: \n{average_by_subject}")
print(f"The average mark per student is: \n{average_by_studnet}")

The average mark per subject is: 
[48.75 61.55 54.   49.2  47.65]
The average mark per student is: 
[56.4 40.6 48.8 47.6 41.  53.  52.4 50.8 44.2 41.8 51.4 64.4 71.6 60.4
 62.6 48.8 53.8 51.6 56.2 47.2]


In [10]:
#2.Highest and lowest per subject
highest_mark_per_subject = np.max(marks,axis=0)
lowest_mark_per_subject = np.min(marks,axis=0)
print(f"The highest mark per subject is: \n{highest_mark_per_subject}")
print(f"The lowest mark per student is: \n{lowest_mark_per_subject}")

The highest mark per subject is: 
[ 94  99 100 100  96]
The lowest mark per student is: 
[12 12 12 11 11]


In [11]:
#3.Overall Class Topper
total_marks_per_student = np.sum(marks,axis=1)
class_topper_mark = np.max(total_marks_per_student)
print(f"The class topper mark is {class_topper_mark}")

The class topper mark is 358


In [12]:
total_marks_per_student

array([282, 203, 244, 238, 205, 265, 262, 254, 221, 209, 257, 322, 358,
       302, 313, 244, 269, 258, 281, 236])