In [2]:
import numpy as np


In [2]:
print(np.__version__)

2.4.6


In [21]:
arr1d = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr1d)
print(arr2d)
print(arr1d.shape)
print(arr2d.shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [4]:
arr1d.ndim

1

In [5]:
arr1d.dtype

dtype('int64')

In [6]:
arr_zeros = np.zeros((2,3),dtype=int)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr_full = np.full((3,3),10)
arr_full

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [3]:
arr_empty = np.empty((3,3))
arr_empty

array([[ 1.27189941e-30, -2.54379882e-30,  6.35949704e-31],
       [-2.54379882e-30,  5.53276243e-30, -1.71706420e-30],
       [ 6.35949704e-31, -1.71706420e-30,  9.85722042e-31]])

In [4]:
arr_empty.ndim

2

Numpy Operations


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [6]:
print(a-b)

[-3 -3 -3]


In [7]:
print(a*b)

[ 4 10 18]


In [8]:
print(b/a)

[4.  2.5 2. ]


In [9]:
print(b//a)

[4 2 2]


In [10]:
c = 5

In [12]:
print(a+b+c)

[10 12 14]


In [14]:
print(a-c)

[-4 -3 -2]


In [15]:
print(a*c)

[ 5 10 15]


In [17]:
d =np.array([[10,20,30],[40,20,60]])


In [18]:
print(a+d)

[[11 22 33]
 [41 22 63]]


Aggregation

In [26]:
arr_agg = np.array([1,2,3,4,5])
print(f"The sum is {np.sum(arr_agg)}")
print(f"The mean is {np.mean(arr_agg)}")
print(f"The median is {np.median(arr_agg)}")
print(f"The max value is {np.max(arr_agg)}")
print(f"The min value is {np.min(arr_agg)}")
print(f"The variance is {np.var(arr_agg)}")
print(f"The standard deviation is {np.std(arr_agg)}")

The sum is 15
The mean is 3.0
The median is 3.0
The max value is 5
The min value is 1
The variance is 2.0
The standard deviation is 1.4142135623730951


In [ ]:
arr_agg = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"The sum is {np.sum(arr_agg)}")
print(f"The sum Column wise is {np.sum(arr_agg,axis=0)}") #Column wise eg : 1+6, 2+7, 3+8 ...
print(f"The sum row wise is {np.sum(arr_agg,axis=1)}") #Row wise wise eg : sum([1,2,3,4,5])
print(f"The sum of elemets greater than 2 is {np.sum(arr_agg[ arr_agg > 2])}") #sum of elements in arr_agg greater than 2
print(f"The mean is {np.mean(arr_agg)}")
print(f"The median is {np.median(arr_agg)}")
print(f"The max value is {np.max(arr_agg)}")
print(f"The min value is {np.min(arr_agg)}")
print(f"The variance is {np.var(arr_agg)}")
print(f"The standard deviation is {np.std(arr_agg)}")

The sum is 55
The sum Column wise is [ 7  9 11 13 15]
The sum row wise is [15 40]
The sum of elemets greater than 2 is 52
The sum of elemets greater than 2 Column wise is 52
The mean is 5.5
The median is 5.5
The max value is 10
The min value is 1
The variance is 8.25
The standard deviation is 2.8722813232690143


Slicing

In [36]:
arr1d_s = np.array([1,2,3,4,5])
arr2d_s = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1d_s[0])
print(arr2d_s[1])
print(arr2d_s[0][4])

1
[ 6  7  8  9 10]
5


In [39]:
print(arr1d_s[1:3])
print(arr2d_s[1][0:3:2])

[2 3]
[6 8]


In [46]:
print(arr1d_s[::-1])
print(arr2d_s[1][::-1])
print(arr2d_s[0:3,2:4])

[5 4 3 2 1]
[10  9  8  7  6]
[[3 4]
 [8 9]]


In [47]:
arr_bool = arr1d_s>1
print(arr1d_s[arr_bool])

[2 3 4 5]


In [52]:
print(arr2d_s[(arr2d_s %2 == 0) & (arr2d_s>2)])

[ 4  6  8 10]


Reshaping
