In [2]:
import numpy as np


In [2]:
print(np.__version__)

2.4.6


In [3]:
arr1d = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr1d)
print(arr2d)
print(arr1d.shape)
print(arr2d.shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [4]:
arr1d.ndim

1

In [5]:
arr1d.dtype

dtype('int64')

In [6]:
arr_zeros = np.zeros((2,3),dtype=int)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr_full = np.full((3,3),10)
arr_full

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [3]:
arr_empty = np.empty((3,3))
arr_empty

array([[ 1.27189941e-30, -2.54379882e-30,  6.35949704e-31],
       [-2.54379882e-30,  5.53276243e-30, -1.71706420e-30],
       [ 6.35949704e-31, -1.71706420e-30,  9.85722042e-31]])

In [4]:
arr_empty.ndim

2

Numpy Operations


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [6]:
print(a-b)

[-3 -3 -3]


In [7]:
print(a*b)

[ 4 10 18]


In [8]:
print(b/a)

[4.  2.5 2. ]


In [9]:
print(b//a)

[4 2 2]


In [10]:
c = 5

In [12]:
print(a+b+c)

[10 12 14]


In [14]:
print(a-c)

[-4 -3 -2]


In [15]:
print(a*c)

[ 5 10 15]


In [17]:
d =np.array([[10,20,30],[40,20,60]])


In [18]:
print(a+d)

[[11 22 33]
 [41 22 63]]
