In [2]:
import numpy as np


In [3]:
print(np.__version__)

2.4.6


In [7]:
arr1d = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr1d)
print(arr2d)
print(arr1d.shape)
print(arr2d.shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [9]:
arr1d.ndim

1

In [10]:
arr1d.dtype

dtype('int64')

In [14]:
arr_zeros = np.zeros((2,3),dtype=int)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
arr_full = np.full((3,3),10)
arr_full

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [17]:
arr_empty = np.empty((3,3))
arr_empty

array([[5.e-323, 5.e-323, 5.e-323],
       [5.e-323, 5.e-323, 5.e-323],
       [5.e-323, 5.e-323, 5.e-323]])